services:
  - type: web
    name: whiteboard-backend
    runtime: node
    rootDir: whiteboard/server
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://live-collaborative-whiteboard.vercel.app
      - key: REDIS_URL
        sync: false
